# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - id: zigdoc
    builder: zig
    flags:
      - -Doptimize=ReleaseSafe
    targets:
      - x86_64-linux
      - x86_64-windows
      - aarch64-linux
      - x86_64-macos
      - aarch64-macos

archives:
  - id: zigdoc
    format: tar.gz
    builds:
      - zigdoc
    files:
      - LICENSE
      - README.md
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  ids:
    - zigdoc
  github:
    owner: tinyzimmer
    name: zigdoc

