name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*

env:
  ZIG_VERSION: master
  BUILD_PARALLELISM: 4

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Run tests
        shell: bash
        run: zig build test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Build
        shell: bash
        run: zig build

      - name: Run Snapshot Release
        uses: goreleaser/goreleaser-action@v6
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --snapshot --clean --parallelism ${{ env.BUILD_PARALLELISM }}

      - name: Run Release
        uses: goreleaser/goreleaser-action@v6
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --parallelism ${{ env.BUILD_PARALLELISM }}
